-- Jalankan SQL ini di Supabase SQL Editor

create table if not exists public.extras (
  id bigint generated by default as identity primary key,
  name text not null unique,
  capacity integer not null default 2 check (capacity >= 0)
);

create table if not exists public.choices (
  id bigint generated by default as identity primary key,
  member_name text not null unique,
  extra_id bigint not null references public.extras(id) on delete cascade,
  created_at timestamptz not null default now()
);

insert into public.extras (name, capacity)
values
('Basket', 2), ('Voli', 2), ('Karate', 2), ('Bulu Tangkis', 2),
('KIR', 2), ('Paduan Suara', 2), ('PMR', 2), ('DC', 2),
('Silat', 2), ('Broadcasting', 2), ('Tari', 2), ('Paskibra', 1),
('Futsal', 1), ('Catur', 1), ('Bahasa Jepang', 1), ('Mading', 1),
('Pramuka', 1)
on conflict (name) do nothing;

alter table public.extras enable row level security;
alter table public.choices enable row level security;

create policy "public read extras"
on public.extras for select
to anon
using (true);

create policy "public update extras"
on public.extras for update
to anon
using (true)
with check (capacity >= 0);

create policy "public read choices"
on public.choices for select
to anon
using (true);

create policy "public insert choices"
on public.choices for insert
to anon
with check (true);

create policy "public update choices"
on public.choices for update
to anon
using (true)
with check (true);

create policy "public delete choices"
on public.choices for delete
to anon
using (true);

-- Catatan keamanan:
-- Policy di atas cocok untuk prototype kelas/lokal.
-- Untuk penggunaan serius, gunakan Supabase Auth dan policy berbasis role admin.
